
# Appearance
appearance:
  mode: system
  color: cyan
  # emerald
# blue, cyan, green, indigo, purple, red, rose, sky, teal, and zinc.
# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Independent University Bangladesh'
    description: 'Jahid Hasan Rony is a reseracher at Independent University, Bangladesh, specializing in computer vision, machine learning, and the AI.'
    twitter: ''
  analytics:
    google_analytics: 'G-5DJD56KQ54'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: false
    show_theme_chooser: true
    logo:
      text: "Jahid Hasan Rony"

# # Site footer
footer:
  copyright:
    notice: '© {year} JH Rony'
#     # license:
#     #   enable: true
#     #   allow_derivatives: false
#     #   share_alike: true
#     #   allow_commercial: false


# # Site footer
# footer:
#   copyright:
#     notice: '© {year} JH Rony. Last updated on {{ .Site.Lastmod.Format "2006-01-02" }}'


# Localization
# locale:
#   date_format: 'Jan 2, 2025'
#   time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
